### ISSUE TITLE
Visual Identification

### ISSUE THREAD

**Issue by MikelThief** [MikelThief/Volta#9]
**Describe the solution you'd like**
I would like to have a set of graphics for an app (assets) that conform to [UWP guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos) and provide visual identification to the app.
Adobe After Effects animation may be supported via [Lottie](https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie)

**Comment by MikelThief** [comment]
@Dreidree any update on this?

**Comment by Dreidree** [comment]
![0C68BECB-E990-4C39-BA32-8F512C5F6D73](https://user-images.githubusercontent.com/39068026/54920330-42757180-4f03-11e9-938b-a5184de0dc7d.png)
![9B6FC4EE-A4D7-4EBE-9FCE-F916BAB20905](https://user-images.githubusercontent.com/39068026/54920332-43a69e80-4f03-11e9-9988-380df6778af6.png)
![28A9F299-18AC-4323-BDE9-BD2830896BD9](https://user-images.githubusercontent.com/39068026/54920334-43a69e80-4f03-11e9-8218-9113235b1625.png)
![391F66A6-3B67-40BB-A636-51F2763A9A08](https://user-images.githubusercontent.com/39068026/54920336-43a69e80-4f03-11e9-8130-e30407957266.png)
![2701F9FA-D818-47C5-A516-F3A3AE40EB16](https://user-images.githubusercontent.com/39068026/54920337-43a69e80-4f03-11e9-8620-fff1bf794fff.png)
![97158E2E-9071-4FDD-A7E6-8BD588E122DC](https://user-images.githubusercontent.com/39068026/54920338-43a69e80-4f03-11e9-8240-758c6d10423c.png)
![CA6EA8A7-F2E4-40DA-BC67-ACAE594A4099](https://user-images.githubusercontent.com/39068026/54920339-443f3500-4f03-11e9-90c3-6a2953300d26.png)
![D31F5E09-FBFA-4D04-B006-EC2E63682F84](https://user-images.githubusercontent.com/39068026/54920340-443f3500-4f03-11e9-8925-53b903f9612e.png)
![F15FDF54-C9A3-489C-B997-8ED245B91BA5](https://user-images.githubusercontent.com/39068026/54920342-44d7cb80-4f03-11e9-9e6a-089bb82d3938.png)

**Comment by Dreidree** [comment]
![F9B7E51C-338D-48DD-AFC2-7AA47EAD426A](https://user-images.githubusercontent.com/39068026/54920363-55884180-4f03-11e9-97c7-3bbfe22bb0d2.png)

**Comment by Dreidree** [comment]
![v1](https://user-images.githubusercontent.com/39068026/54920374-5de07c80-4f03-11e9-8b85-a201637160ab.jpg)

**Comment by MikelThief** [comment]
@Dreidree the lat one fits great! Waiting for an asset collection in a PR! :)
